# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/hassio-addons/base:20.0.1
  amd64: ghcr.io/hassio-addons/base:20.0.1
  armhf: ghcr.io/hassio-addons/base:20.0.1
  i386: ghcr.io/hassio-addons/base:20.0.1
labels:
  org.opencontainers.image.title: "Sequential Thinking MCP add-on"
  org.opencontainers.image.description: "Sequential Thinking MCP add-on for Home Assistant"
  org.opencontainers.image.source: "https://github.com/DjFabFab/ha-mcp-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
